language: php

before_install:
 - echo -e "-----BEGIN OPENSSH PRIVATE KEY-----\n$(echo $SSH_PRIVATE_KEY | fold -w71)\n-----END OPENSSH PRIVATE KEY-----" > "$HOME/.ssh/id_ed25519"
 - chmod 600 "$HOME/.ssh/id_ed25519"

install:
 - composer install

before_script:
 - git clone git@github.com:phpseclib/phpseclib.git
 - git clone git@github.com:phpseclib/api.phpseclib.org.git
 - find api.phpseclib.org -mindepth 1 -maxdepth 1 -type d -not -name .git -exec rm -rf {} \;

script:
 - vendor/bin/doctum.php update doctum.conf.php

after_success:
 - cd api.phpseclib.org
 - git add . && git commit -m "Updated via Travis CI." && git push
